filebeat.inputs:
  - type: container
    paths:
      - '/var/lib/docker/containers/*/*.log'
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true

    # Only collect logs from beewaf container
    condition:
      contains:
        docker.container.name: "beewaf_sklearn"

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: false
